//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketApp.TeamServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Team", Namespace="http://schemas.datacontract.org/2004/07/TeamService")]
    [System.SerializableAttribute()]
    public partial class Team : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamID {
            get {
                return this.TeamIDField;
            }
            set {
                if ((this.TeamIDField.Equals(value) != true)) {
                    this.TeamIDField = value;
                    this.RaisePropertyChanged("TeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeamServiceReference.ITeamService")]
    public interface ITeamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeams", ReplyAction="http://tempuri.org/ITeamService/GetTeamsResponse")]
        System.Data.DataSet GetTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeams", ReplyAction="http://tempuri.org/ITeamService/GetTeamsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/CreateTeam", ReplyAction="http://tempuri.org/ITeamService/CreateTeamResponse")]
        void CreateTeam(CricketApp.TeamServiceReference.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/CreateTeam", ReplyAction="http://tempuri.org/ITeamService/CreateTeamResponse")]
        System.Threading.Tasks.Task CreateTeamAsync(CricketApp.TeamServiceReference.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeamId", ReplyAction="http://tempuri.org/ITeamService/GetTeamIdResponse")]
        int GetTeamId(string tname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeamId", ReplyAction="http://tempuri.org/ITeamService/GetTeamIdResponse")]
        System.Threading.Tasks.Task<int> GetTeamIdAsync(string tname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetScoreCardA", ReplyAction="http://tempuri.org/ITeamService/GetScoreCardAResponse")]
        System.Data.DataSet GetScoreCardA(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetScoreCardA", ReplyAction="http://tempuri.org/ITeamService/GetScoreCardAResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetScoreCardAAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetScoreCardB", ReplyAction="http://tempuri.org/ITeamService/GetScoreCardBResponse")]
        System.Data.DataSet GetScoreCardB(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetScoreCardB", ReplyAction="http://tempuri.org/ITeamService/GetScoreCardBResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetScoreCardBAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTotalScore", ReplyAction="http://tempuri.org/ITeamService/GetTotalScoreResponse")]
        System.Data.DataSet GetTotalScore(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTotalScore", ReplyAction="http://tempuri.org/ITeamService/GetTotalScoreResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTotalScoreAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTournament", ReplyAction="http://tempuri.org/ITeamService/GetTournamentResponse")]
        System.Data.DataSet GetTournament();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTournament", ReplyAction="http://tempuri.org/ITeamService/GetTournamentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTournamentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeamById", ReplyAction="http://tempuri.org/ITeamService/GetTeamByIdResponse")]
        string GetTeamById(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/GetTeamById", ReplyAction="http://tempuri.org/ITeamService/GetTeamByIdResponse")]
        System.Threading.Tasks.Task<string> GetTeamByIdAsync(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/updateDetails", ReplyAction="http://tempuri.org/ITeamService/updateDetailsResponse")]
        void updateDetails(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeamService/updateDetails", ReplyAction="http://tempuri.org/ITeamService/updateDetailsResponse")]
        System.Threading.Tasks.Task updateDetailsAsync(int matchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeamServiceChannel : CricketApp.TeamServiceReference.ITeamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeamServiceClient : System.ServiceModel.ClientBase<CricketApp.TeamServiceReference.ITeamService>, CricketApp.TeamServiceReference.ITeamService {
        
        public TeamServiceClient() {
        }
        
        public TeamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTeams() {
            return base.Channel.GetTeams();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTeamsAsync() {
            return base.Channel.GetTeamsAsync();
        }
        
        public void CreateTeam(CricketApp.TeamServiceReference.Team team) {
            base.Channel.CreateTeam(team);
        }
        
        public System.Threading.Tasks.Task CreateTeamAsync(CricketApp.TeamServiceReference.Team team) {
            return base.Channel.CreateTeamAsync(team);
        }
        
        public int GetTeamId(string tname) {
            return base.Channel.GetTeamId(tname);
        }
        
        public System.Threading.Tasks.Task<int> GetTeamIdAsync(string tname) {
            return base.Channel.GetTeamIdAsync(tname);
        }
        
        public System.Data.DataSet GetScoreCardA(int matchId) {
            return base.Channel.GetScoreCardA(matchId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetScoreCardAAsync(int matchId) {
            return base.Channel.GetScoreCardAAsync(matchId);
        }
        
        public System.Data.DataSet GetScoreCardB(int matchId) {
            return base.Channel.GetScoreCardB(matchId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetScoreCardBAsync(int matchId) {
            return base.Channel.GetScoreCardBAsync(matchId);
        }
        
        public System.Data.DataSet GetTotalScore(int matchId) {
            return base.Channel.GetTotalScore(matchId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTotalScoreAsync(int matchId) {
            return base.Channel.GetTotalScoreAsync(matchId);
        }
        
        public System.Data.DataSet GetTournament() {
            return base.Channel.GetTournament();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTournamentAsync() {
            return base.Channel.GetTournamentAsync();
        }
        
        public string GetTeamById(int teamId) {
            return base.Channel.GetTeamById(teamId);
        }
        
        public System.Threading.Tasks.Task<string> GetTeamByIdAsync(int teamId) {
            return base.Channel.GetTeamByIdAsync(teamId);
        }
        
        public void updateDetails(int matchId) {
            base.Channel.updateDetails(matchId);
        }
        
        public System.Threading.Tasks.Task updateDetailsAsync(int matchId) {
            return base.Channel.updateDetailsAsync(matchId);
        }
    }
}
